export const REGISTRATION_URL = 'http://www.qa.way2automation.com'
export const FIXTURE_ACTIONS_FILE = 'categoryActions'
export const FIXTURE_USERS_FILE = 'users'
export const SELENIUM_PROJECT_URL = 'https://www.selenium-tutorial.com/p/automation-architect-in-selenium-7-live-projects'
export const SELENIUM_PROJECT_NAME = 'Automation Architect in Selenium - 7 Live Projects'
export const ORDER_SUMMARY_URL = 'https://checkout.teachable.com/secure/673/checkout/order_bgx7c3pv'